
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyectfinal.cup;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int ASTHERISK = 29;
  public static final int DOSPUNTOS = 6;
  public static final int KEYWORDS = 12;
  public static final int CHART = 41;
  public static final int DESCRIPTION = 11;
  public static final int Y = 26;
  public static final int X = 25;
  public static final int INCREMENT = 31;
  public static final int WORD = 8;
  public static final int LEGENDPOSITION = 24;
  public static final int ASSIGNMENT = 33;
  public static final int MULTIPLICATIONEQUAL = 34;
  public static final int EQUALS = 44;
  public static final int CATEGORY = 19;
  public static final int CORCHETEC = 5;
  public static final int GREATER = 46;
  public static final int CORCHETEA = 4;
  public static final int LESS = 47;
  public static final int MINUS = 28;
  public static final int DECREMENT = 32;
  public static final int FONTFAMILY = 16;
  public static final int DATA = 18;
  public static final int POINTS = 39;
  public static final int LESSEQUAL = 49;
  public static final int COLORWORD = 9;
  public static final int COMMA = 7;
  public static final int DIFFERENT = 45;
  public static final int PLUS = 27;
  public static final int BACKGROUNDCOLOR = 15;
  public static final int FONTSIZE = 17;
  public static final int EOF = 0;
  public static final int SIZE = 37;
  public static final int error = 1;
  public static final int NUMBER = 36;
  public static final int NAME = 38;
  public static final int COLOR = 21;
  public static final int GREATEREQUAL = 48;
  public static final int HEADER = 13;
  public static final int TITLE = 10;
  public static final int DIVISIONEQUAL = 35;
  public static final int XAXISLABEL = 42;
  public static final int LLAVECORCHETEC = 3;
  public static final int COPYRIGHT = 23;
  public static final int LLAVECORCHETEA = 2;
  public static final int FOOTER = 14;
  public static final int LINESTYLE = 40;
  public static final int VALUE = 20;
  public static final int LABEL = 22;
  public static final int DIVISION = 30;
  public static final int YAXISLABEL = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVECORCHETEA",
  "LLAVECORCHETEC",
  "CORCHETEA",
  "CORCHETEC",
  "DOSPUNTOS",
  "COMMA",
  "WORD",
  "COLORWORD",
  "TITLE",
  "DESCRIPTION",
  "KEYWORDS",
  "HEADER",
  "FOOTER",
  "BACKGROUNDCOLOR",
  "FONTFAMILY",
  "FONTSIZE",
  "DATA",
  "CATEGORY",
  "VALUE",
  "COLOR",
  "LABEL",
  "COPYRIGHT",
  "LEGENDPOSITION",
  "X",
  "Y",
  "PLUS",
  "MINUS",
  "ASTHERISK",
  "DIVISION",
  "INCREMENT",
  "DECREMENT",
  "ASSIGNMENT",
  "MULTIPLICATIONEQUAL",
  "DIVISIONEQUAL",
  "NUMBER",
  "SIZE",
  "NAME",
  "POINTS",
  "LINESTYLE",
  "CHART",
  "XAXISLABEL",
  "YAXISLABEL",
  "EQUALS",
  "DIFFERENT",
  "GREATER",
  "LESS",
  "GREATEREQUAL",
  "LESSEQUAL"
  };
}

